### ISSUE TITLE
haringuyen01.crfnetwork.cyou

### ISSUE THREAD

**Issue by haringuyen01** [codingreshapefuture/Community#35]
+ Subdomain (required): haringuyen01.crfnetwork.cyou

+ Owner (required): https://github.com/haringuyen01/
  
+ Project (optinal): https://github.com/<username>/<repo>

+ Contact infor (required): haringuyen01@gmail.com

+ Additional (optinal): Thank you ^^

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `haringuyen01.github.io` -> `haringuyen01.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
