### ISSUE TITLE
chungnguyen.crfnetwork.cyou

### ISSUE THREAD

**Issue by chungngx** [codingreshapefuture/Community#36]
+ Subdomain (required): chungnguyen.crfnetwork.cyou

+ Owner (required): https://github.com/chungngx/
  
+ Project (optinal): https://github.com/<username>/<repo>

+ Contact infor (required): chung24082003@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `chungnguyen.github.io` -> `chungngx.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
