### ISSUE TITLE
81devgl-blog.crfnetwork.cyou

### ISSUE THREAD

**Issue by 81CuongVn** [codingreshapefuture/Community#38]
+ Subdomain (required): 81devgl-blog.crfnetwork.cyou

+ Owner (required): https://github.com/81CuongVn
  
+ Project (optinal): https://github.com/81devGL/chakra-portfolio

+ Contact infor (required): alan45walker12@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `81CuongVn.github.io.` -> `81devgl-blog.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
