### ISSUE TITLE
<nxdinh94>.crfnetwork.cyou

### ISSUE THREAD

**Issue by nxdinh11** [codingreshapefuture/Community#39]
+ Subdomain (required): <nxdinh942>.crfnetwork.cyou

+ Owner (required): https://github.com/<nxdinh11>/
  
+ Project (optinal): https://github.com/<username>/<repo>

+ Contact infor (required): nguyenxuandinh336@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
wrong format

**Comment by nxdinh11** [comment]
+ Subdomain (required): nxdinh942.crfnetwork.cyou

+ Owner (required): https://github.com/nxdinh11/
  
+ Project (optinal): https://github.com/nxdinh11/SQL_fork

+ Contact infor (required): nguyenxuandinh336@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**FORMAT ERROR**: :bangbang:

Format error, please read the [Register domain Wiki](https://github.com/codingreshapefuture/Community/wiki/Register-Domain) carefully and request again!
