### ISSUE TITLE
markdevnodo.crfnetwork.cyou

### ISSUE THREAD

**Issue by ledinhducmanh** [codingreshapefuture/Community#41]
+ Subdomain (required): markdevnodo.crfnetwork.cyou

+ Owner (required): https://github.com/ledinhducmanh/
  
+ Project (optinal): https://github.com/ledinhducmanh/New-Profile

+ Contact infor (required): ledinhducmanh66@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `ledinhducmanh.github.io` -> `markdevnodo.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
