### ISSUE TITLE
nxdinh942.crfnetwork.cyou

### ISSUE THREAD

**Issue by nxdinh11** [codingreshapefuture/Community#42]
+ Subdomain (required): nxdinh94.crfnetwork.cyou

+ Owner (required): https://github.com/nxdinh11/
  
+ Project (optinal): https://github.com/nxdinh11/SQL_Fork

+ Contact infor (required): nguyenxuandinh336@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `nxdinh11.github.io` -> `nxdinh942.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
