### ISSUE TITLE
Minhnguyen1804.crfnetwork.cyou

### ISSUE THREAD

**Issue by Minhnguyen1804** [codingreshapefuture/Community#48]
+ Subdomain (required): Minhnguyen1804.crfnetwork.cyou

+ Owner (required): https://github.com/Minhnguyen1804/
  
+ Project (optinal): https://github.com/Minhnguyen1804/<repo>

+ Contact infor (required):tqtddv1804@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `Minhnguyen1804.github.io` -> `Minhnguyen1804.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
Check out the Issue #51
