### ISSUE TITLE
abcxyz.crfnetwork.cyou

### ISSUE THREAD

**Issue by ThongPham08** [codingreshapefuture/Community#50]
+ Subdomain (required): abcxyz.crfnetwork.cyou

+ Owner (required): https://github.com/ThongPham08/
  
+ Project (optinal): https://github.com/<username>/<repo>

+ Contact infor (required): phamtranminhthong272008@gmail.com
+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
Are you spamming?

**Comment by ThongPham08** [comment]
> Are you spamming?

i'm just dumb so that i forgot to delete the <> so i need to do it again, sorry for mistaken

**Comment by ThongPham08** [comment]
please verify my domain, i'm sorry for my mistake

**Comment by lucthienphong1120** [comment]
Okay, wait for me in the morning

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `thongpham08.github.io` -> `abcxyz.crfnetwork.cyou`.

**Comment by lucthienphong1120** [comment]
#51
