### ISSUE TITLE
lovestory.crfnetwork.cyou

### ISSUE THREAD

**Issue by manmandh** [codingreshapefuture/Community#52]
+ Subdomain (required): lovestory.crfnetwork.cyou

+ Owner (required): https://github.com/manmandh/
  
+ Project (optinal): https://github.com/dazai/<repo>

+ Contact infor (required): tranmanman91@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
Project is not a project

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `manmandh.github.io` -> `lovestory.crfnetwork.cyou`.
