### ISSUE TITLE
2hstore.crfnetwork.cyou

### ISSUE THREAD

**Issue by linhnv4dev** [codingreshapefuture/Community#53]
+ Subdomain (required): 2hstore.crfnetwork.cyou

+ Owner (required): https://github.com/deathrexx4524/
  
+ Project (optinal): https://github.com/deathrexx4524/2HStore

+ Contact infor (required): vanlinh4524@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `deathrexx4524.github.io` -> `2hstore.crfnetwork.cyou`.
