### ISSUE TITLE
sportclub.crfnetwork.cyou

### ISSUE THREAD

**Issue by HUNGTRIDOAN** [codingreshapefuture/Community#54]
+ Subdomain (required): sportclub.crfnetwork.cyou

+ Owner (required): https://github.com/HUNGTRIDOAN/
  
+ Project (optinal): https://github.com/HUNGTRIDOAN/sportclub

+ Contact infor (required): koikoidth12@gmail.com

+ Additional (optinal): Add any message or screenshots if you want to request here.

**Comment by lucthienphong1120** [comment]
**SUCCESSFUL**: :heavy_check_mark:

Your domain name has been approved with the cname record `HUNGTRIDOAN.github.io` -> `sportclub.crfnetwork.cyou`.
